//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublixRDPEnhancer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PublixRDPEnhancer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program allows Publix I/S Associates to automate the RDP session file modifcations needed to connect to their machine at the office. The Citrix Gateway by default disables the Remote Audio Capture Device (Remote Microphone), which is inconvenient when Associates have multiple Teams meetings throughout the day. Instead of opening up the RDP session file in Notepad++ and modifying the setting everytime you need to remote to your office machine, this program will automate that process and establish the RD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aboutInfo {
            get {
                return ResourceManager.GetString("aboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Auto Click function will automatically click wherever your mouse pointer is randomly between 10 to 60 seconds (or 10000 ms to 60000 ms); this is to ensure your RDP session stays alive when you are away from keyboard and locked your desktop (ex. away for lunch, appointment, etc.). I have experienced locks outs that happen from time to time within 2 minutes or so on my old personal laptop, which can be frustrating as you would need to download a new RDP file (and possibly log back in to Citrix to do so) a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string autoClickHelp {
            get {
                return ResourceManager.GetString("autoClickHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connectButton {
            get {
                object obj = ResourceManager.GetObject("connectButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDP Not Connected.
        /// </summary>
        internal static string notConnected {
            get {
                return ResourceManager.GetString("notConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap preconnectButton {
            get {
                object obj = ResourceManager.GetObject("preconnectButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PUBLIX_brandmark {
            get {
                object obj = ResourceManager.GetObject("PUBLIX_brandmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDP Session Established.
        /// </summary>
        internal static string sessionEst {
            get {
                return ResourceManager.GetString("sessionEst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Auto Click To Keep Session Alive.
        /// </summary>
        internal static string startAC {
            get {
                return ResourceManager.GetString("startAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Auto Click To Keep Session Alive.
        /// </summary>
        internal static string stopAC {
            get {
                return ResourceManager.GetString("stopAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Clicking Connect will delete all RDP files in your Downloads directory except the latest one (not including RDP files within subfolders of the directory). This program will modify the RDP file contents to set your desired settings, then automatically open and establish the RDP session.
        ///
        ///Make sure you have downloaded your machine&apos;s latest RDP Session File or an error may occur!.
        /// </summary>
        internal static string warningInfo {
            get {
                return ResourceManager.GetString("warningInfo", resourceCulture);
            }
        }
    }
}
